version: '3.8'

services:
  dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 5000:5000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/TuanAnh/src/app
      - /TuanAnh/src/app/node_modules
    restart: unless-stopped
    env_file:
      - .env
  prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 5000:5000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/TuanAnh/src/app
      - /TuanAnh/src/app/node_modules
    restart: unless-stopped
    env_file:
      - .env

networks:
  nesjs-network:
